// Handle a Rejected Promise with cateh
// When a promise is rejected the catch method is used with the following syntax:
myPromise.catch(error => {

});
// where the error argument is passed to the reject method.